#!/usr/bin/env bash
set -euo pipefail

SITE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_ROOT="${SOURCE_ROOT:-$(cd "$SITE_ROOT/.." && pwd)}"
PRESENTATIONS_DIR="$SITE_ROOT/presentations"
DATA_DIR="$SITE_ROOT/_data"
DATA_FILE="$DATA_DIR/presentations.yml"
STRICT_SYNC="${STRICT_SYNC:-false}"

rm -rf "$PRESENTATIONS_DIR"
mkdir -p "$PRESENTATIONS_DIR" "$DATA_DIR"

escape_yaml() {
  local value="$1"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

cat > "$DATA_FILE" <<'YAML'
# Generated by scripts/sync-presentations.sh
YAML

ENTRIES=$(cat <<'EOF'
skraft-agents|SKRAFT - Agents|SKRAFT|skraft-plugin|presentation-skraft-agents.html|private
meetup-coding-with-ai|Meetup - SKRAFT Workflow Demo|meetup-coding-with-ai|meetup-coding-with-ai|meetup-coding-with-ai.html|public
EOF
)

while IFS='|' read -r key title project repo source_file visibility; do
  [[ -n "$key" ]] || continue

  src_repo_path="$SOURCE_ROOT/$repo"
  src_file_path="$src_repo_path/$source_file"
  dest_presentation_dir="$PRESENTATIONS_DIR/$key"
  dest_file_path="$dest_presentation_dir/index.html"
  published_url="/presentations/$key/"
  dest_assets_dir="$dest_presentation_dir/assets"
  src_assets_dir="$src_repo_path/assets"

  if [[ ! -f "$src_file_path" ]]; then
    echo "[WARN] Missing source file: $src_file_path"
    if [[ "$STRICT_SYNC" == "true" ]]; then
      exit 1
    fi
    continue
  fi

  mkdir -p "$dest_presentation_dir"
  cp "$src_file_path" "$dest_file_path"

  # If the source repository has an assets folder, publish it under a repo-scoped path.
  if [[ -d "$src_assets_dir" ]]; then
    mkdir -p "$dest_assets_dir"
    rsync -a "$src_assets_dir/" "$dest_assets_dir/"

    # Normalize links to colocated assets in the presentation folder.
    perl -0pi -e "s#/(presentations/)?assets/$repo/#assets/#g; s#(src|href)=([\"'])\./assets/#\1=\2assets/#g" "$dest_file_path"
  fi

  updated_at="unknown"
  commit_hash="unknown"

  if git -C "$src_repo_path" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    updated_at="$(git -C "$src_repo_path" log -1 --format=%cs -- "$source_file" || echo unknown)"
    commit_hash="$(git -C "$src_repo_path" log -1 --format=%h -- "$source_file" || echo unknown)"
  fi

  {
    echo "- id: $(escape_yaml "$key")"
    echo "  title: $(escape_yaml "$title")"
    echo "  project: $(escape_yaml "$project")"
    echo "  source_repository: $(escape_yaml "$repo")"
    echo "  source_path: $(escape_yaml "$source_file")"
    echo "  visibility: $(escape_yaml "$visibility")"
    echo "  updated_at: $(escape_yaml "$updated_at")"
    echo "  source_commit: $(escape_yaml "$commit_hash")"
    echo "  url: $(escape_yaml "$published_url")"
  } >> "$DATA_FILE"
done <<< "$ENTRIES"

echo "Presentations synced into: $PRESENTATIONS_DIR"
echo "Data file generated: $DATA_FILE"
